const AppError = require('../utils/AppError');

const errorHandler = (err, req, res, next) => {
  // Se o erro jÃ¡ Ã© um AppError que nÃ³s criamos, usamos o status e msg dele
  if (err instanceof AppError) {
    return res.status(err.statusCode).json({
      status: err.status,
      message: err.message,
    });
  }

  console.error('ERRO INESPERADO ğŸ’¥', err);

  return res.status(500).json({
    status: 'error',
    message: 'Internal Server Error',
  });
};

module.exports = errorHandler;
